[package]
name = "infinite_vec"
version = "0.0.1"
edition = "2021"
authors = ["Tim (Theemathas) Chirananthavat <theemathas@gmail.com>"]
description = "A lazily-populated infinite Vec-like data structure."
license = "MIT"
keywords = ["infinite", "data-structures", "iterator", "lazy"]
categories = ["data-structures", "iterators", "caching"]
# Don't publish yet. Also, make a repository link.
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
